# カメラ設定
camera:
  resolution_width: 5472     # 解像度（幅）
  resolution_height: 3468    # 解像度（高さ）
  frame_rate: 10            # フレームレート
  image_size:
    x5: [2.711, 1.721]     # 5x倍率時の撮影範囲 (mm)
    x10: [1.314, 0.831]     # 10x倍率時の撮影範囲 (mm)
    x20: [0.653, 0.415]     # 20x倍率時の撮影範囲 (mm)
    x50: [0.261, 0.168]     # 50x倍率時の撮影範囲 (mm)
    x100: [0.132, 0.84]    # 100x倍率時の撮影範囲 (mm)

# ステージ設定
stage:
  com_port: "COM3"          # COMポート
  baud_rate: 9600           # ボーレート
  timeout: 5.0              # 通信タイムアウト（秒）
  x_min: -50.0              # X軸最小座標
  x_max: 50.0               # X軸最大座標
  y_min: -50.0              # Y軸最小座標
  y_max: 50.0               # Y軸最大座標
  pulses_per_mm: 1000       # パルス/mm変換係数（要調整）
  speed:
    s1: 50             # S1速度（PPS）
    s2: 200
    s3: 1000
    s4: 5000
    s5: 10000
    s6: 20000
    accelation_time: 200  # 加減速時間（ms）

# スティッチング設定
stitching:
  type: "advanced"              # スティッチングタイプ (simple/advanced)
  overlap_ratio: 0.1        # 画像重複率 (0.0-0.5)
  max_images: 100           # 最大画像数
  image_format: "PNG"       # 保存形式 (PNG/JPEG/TIFF)
  compression_quality: 95   # 圧縮品質 (1-100)
  auto_blend: true          # 自動ブレンド
  blend_method: "linear"    # ブレンド方式 (linear/multiband/feather)

# GUI設定
gui:
  window_width: 1200        # ウィンドウ幅
  window_height: 800        # ウィンドウ高さ
  theme: "light"            # テーマ (light/dark)
  show_coordinates: true    # 座標表示
  show_scale_bar: true      # スケールバー表示

# アプリケーション設定
mock: false
log_level: "INFO"           # ログレベル (DEBUG/INFO/WARNING/ERROR)
data_directory: "data"      # データ保存ディレクトリ
backup_directory: "backup" # バックアップディレクトリ
temp_directory: "temp"      # 一時ファイルディレクトリ